


###  registration
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "name" : "imran sarkar",
    "email" : "imransarkar@gmail.com",
    "password": "new_password"
}


### login
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "email" : "imransarkar@gmail.com",
    "password": "new_password"
}

### get user

GET http://localhost:8000/api/users
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGY5ZmM0ZWZjY2NkNjMwM2YzOWQ0ZCIsImlhdCI6MTY0NTI4MjQ1MX0.ua7XZPhcDts_aCjGqlpE4zU2aC1ovCp3F78q6kQJKkE


